#!/bin/bash
# Script to help get Stripe test API keys

echo "🔑 Stripe Test API Keys Setup"
echo "=============================="
echo ""
echo "To get your Stripe test API keys:"
echo ""
echo "1. Go to: https://dashboard.stripe.com/test/apikeys"
echo "   (Make sure you're in Test mode - toggle in top right)"
echo ""
echo "2. You'll find two keys:"
echo "   - Publishable key (starts with pk_test_)"
echo "   - Secret key (starts with sk_test_)"
echo ""
echo "3. Click 'Reveal test key' to see your secret key"
echo ""
echo "4. Add these to your .env.local file:"
echo ""
echo "   STRIPE_SECRET_KEY=sk_test_..."
echo "   NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_..."
echo ""
echo "5. For webhooks, run in a separate terminal:"
echo "   stripe listen --forward-to localhost:3000/api/stripe/webhook"
echo ""
echo "   Then copy the 'webhook signing secret' (starts with whsec_)"
echo "   and add it to .env.local as:"
echo "   STRIPE_WEBHOOK_SECRET=whsec_..."
echo ""
echo "📝 Quick setup:"
echo "After getting your keys, create .env.local with:"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL=http://localhost:54331"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=your_anon_key"
echo "SUPABASE_SERVICE_ROLE_KEY=your_service_role_key"
echo ""
echo "STRIPE_SECRET_KEY=sk_test_..."
echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_..."
echo "STRIPE_WEBHOOK_SECRET=whsec_..."
echo ""
